=== kagrawal-tibco/svnToGit/runtime/mm/tea/xsds/AccumulatorPluginConfig.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
		   xmlns:jxb="http://java.sun.com/xml/ns/jaxb" 
		   jxb:version="2.0" 
		   xmlns="http://www.tibco.com/cep/bemm/monitoring/metric/config/collectorconfig"  
		   targetNamespace="http://www.tibco.com/cep/bemm/monitoring/metric/config/collectorconfig"  
		   xmlns:tns="http://www.tibco.com/cep/bemm/monitoring/metric/config/collectorconfig"
		   elementFormDefault="qualified">

	 <xsd:element name="AccumulatorPlugin">
       <xsd:complexType>	
         <xsd:sequence>
		   <xsd:element   name="classpath" type="Classpath" />
		   <xsd:element   name="config" type="PluginConfig" />		   
		  <!--  <xsd:element   name="mappings" type="Mappings" /> -->
		   <xsd:element   name="map-entry" type="MapEntry" minOccurs="0" maxOccurs="unbounded" />
         </xsd:sequence>
		 <xsd:attribute   name="name" type="xsd:string" use="required"/>
		 <xsd:attribute   name="className" type="xsd:string" use="required"/>
		 <xsd:attribute   name="spm_schema" type="xsd:string" use="required"/>
       </xsd:complexType>
     </xsd:element>
	 
	 <xsd:complexType name="Classpath">
		<xsd:sequence>
        	<xsd:element name="path" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>		
        </xsd:sequence>
     </xsd:complexType>
	
	 <xsd:complexType name="PluginConfig">
		<xsd:sequence>
        	<xsd:element name="property" type="Property" minOccurs="0" maxOccurs="unbounded"/>		
        </xsd:sequence>
     </xsd:complexType>
	 
	 <xsd:complexType name="Property">
        	<xsd:attribute name="name" type="xsd:string"/>
			<xsd:attribute name="value" type="xsd:string"/>
			<xsd:attribute name="type" type="xsd:string"/>
     </xsd:complexType>
     
     <xsd:complexType name="MapEntry">
		<xsd:sequence>
        	<xsd:element name="mapping" type="Mapping" minOccurs="0" maxOccurs="unbounded"/>
        	<xsd:element name="multi-mapping" type="MultiMapping" minOccurs="0" maxOccurs="unbounded"/>		
        </xsd:sequence>
     </xsd:complexType>
	 
	 <xsd:complexType name="Mappings">
		<xsd:sequence>
        	<xsd:element name="mapping" type="Mapping" minOccurs="0" maxOccurs="unbounded"/>		
        	<xsd:element name="multi-mapping" type="MultiMapping" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
     </xsd:complexType> 
     
     <xsd:complexType name="MultiMapping">
		<xsd:sequence>
			<xsd:element name="arg" type="Property" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="target-mapping" type="TargetMapping" minOccurs="0" maxOccurs="unbounded"/>
       	</xsd:sequence>
       	<xsd:attribute   name="type" type="xsd:string" use="required"/>	
       	<xsd:attribute   name="source" type="xsd:string" use="required"/>
		<xsd:attribute   name="name" type="xsd:string" use="required"/>
		<xsd:attribute   name="datatype" type="xsd:string" use="required"/>
		<xsd:attribute   name="entity" type="xsd:string" />
     </xsd:complexType>
	
	 <xsd:complexType name="Mapping">
		<xsd:sequence>
			<xsd:element name="arg" type="Property" minOccurs="0" maxOccurs="unbounded" />	
			<xsd:element name="target-mapping" type="TargetMapping" minOccurs="0" maxOccurs="unbounded"/>	
        </xsd:sequence>
		<xsd:attribute   name="source" type="xsd:string" use="required"/>
		<xsd:attribute   name="target" type="xsd:string" use="required"/>
		<xsd:attribute   name="datatype" type="xsd:string" use="required"/>
		<xsd:attribute   name="type" type="xsd:string" use="required"/>		   
		<xsd:attribute   name="defaultValue" type="xsd:string" />
		<xsd:attribute   name="entity" type="xsd:string" />
		<xsd:attribute   name="beentity" type="xsd:string" />
		<xsd:attribute   name="isMultiple" type="xsd:boolean" />
     </xsd:complexType>
	
	<xsd:complexType name="TargetMapping">
		<xsd:sequence>
			<xsd:element name="arg" type="Property" minOccurs="0" maxOccurs="unbounded" />	
		</xsd:sequence>	
	    <xsd:attribute   name="source" type="xsd:string" use="required"/>
		<xsd:attribute   name="target" type="xsd:string" use="required"/>
		<xsd:attribute   name="datatype" type="xsd:string" use="required"/>
		<xsd:attribute   name="defaultValue" type="xsd:string" />
		<xsd:attribute   name="interceptorName" type="xsd:string"/>
	</xsd:complexType>
     
</xsd:schema>

=== kagrawal-tibco/svnToGit/runtime/mm/tea/config/plugins/beteagent_plugin.xml
<?xml version="1.0" encoding="UTF-8"?>

<AccumulatorPlugin 
 xmlns="http://www.tibco.com/cep/bemm/monitoring/metric/config/collectorconfig" 
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:schemaLocation="http://www.tibco.com/cep/bemm/monitoring/metric/config/collectorconfig ../xsds/AccumulatorPluginConfig.xsd "
 name="JMXAdapter" 
 className="com.tibco.cep.bemm.monitoring.metric.probe.accumulator.jmx.BETeaAgentJmxAccumulator" 
 spm_schema="BETEA">
 
	<config>
		<property name="poll-interval" value="15000" />
		<property name="system-plugin" value="true" />
	</config>
	
	<map-entry >
		 <!-- MEMORY -->
	     <mapping source="java.lang:type=Memory" type="attribute"  >
	     	<target-mapping source="HeapMemoryUsage.max"       target="maxmemsize"       datatype="DOUBLE" defaultValue="0" />
	     	<target-mapping source="HeapMemoryUsage.used"      target="usedmemsize"      datatype="DOUBLE" defaultValue="0"  /> 
	     </mapping>
	     <!-- CPU -->
	     <mapping source="java.lang:type=OperatingSystem" type="attribute" >
			<target-mapping source="ProcessCpuLoad" 		target="cpuusage" 	datatype="DOUBLE"   defaultValue="0" />
		 </mapping>
		 <!-- THREADING -->
	      <mapping source="java.lang:type=Threading" type="attribute">
	         <target-mapping source="ThreadCount" target="threadcount" datatype="LONG" defaultValue="0" />
	      </mapping>
	      <mapping source="java.lang:type=Threading" type="operation">
	         <target-mapping source="findDeadlockedThreads" target="deadlockedthreadcount" datatype="LONG" defaultValue="0" />
	      </mapping>
		 
		<!-- RULES -->
		<!-- <multi-mapping source="be.teagent.service.rules:type=RuleService" type="attribute" name="RuleStatistics">
			<target-mapping source="RuleName" 		target="statRuleName" 	datatype="STRING"       defaultValue="na" interceptorName="com.tibco.cep.bemm.monitoring.metric.interceptor.impl.RuleNameJmxInterceptor" />
			<target-mapping source="RuleName" 		target="ruleEntity" 	datatype="STRING"       defaultValue="na" interceptorName="com.tibco.cep.bemm.monitoring.metric.interceptor.impl.RuleNameJmxInterceptor" />
			<target-mapping source="RuleName" 		target="ruleApp" 	    datatype="STRING"       defaultValue="na" interceptorName="com.tibco.cep.bemm.monitoring.metric.interceptor.impl.RuleNameJmxInterceptor" />
			<target-mapping source="TotalTime" 		target="totalTime" 	    datatype="LONG"         defaultValue="0" />
			<target-mapping source="TotalEval" 		target="evalCount" 	    datatype="LONG"         defaultValue="0" />
			<target-mapping source="AvgTime" 		target="avgTime" 	    datatype="DOUBLE"       defaultValue="0" />
		</multi-mapping> -->
     	
     </map-entry>

</AccumulatorPlugin>
